---
- name: patching kernel
  hosts: "{{hostname}}"
  become: yes
  become_method: sudo
  tasks:

    - name: confirm kernel version
      # vars:
      #   kernel_version: "{{kernel}}"
      #   register: current_kernel
      # - debug: msg="{{ current_kernel.kernel }}"
      shell: uname -a
      register: kernel_version
    - debug: var=kernel_version.stdout


    # - name: install epel-release
    #   yum:
    #     name: epel-release
    #     state: latest
    - name: Add repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/